### ISSUE TITLE
it's works in dockerfile container image?

### ISSUE THREAD

**Issue by qweralfredo** [quackscience/duckdb-extension-httpserver#18]
i'm creating a simple duckdb container with the commands sent by duckdb -cmd ".read startup.sql":

startup.sql content's

INSTALL httpserver FROM community;
LOAD httpserver;
SELECT httpserve_start('localhost', 9999, 'user:pass'); 

select 24;

the content of the dockerfile is:

FROM ubuntu:20.04

WORKDIR /app

RUN apt-get update && apt-get install -y wget unzip iptables nano curl

RUN wget https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip -O duckdb.zip \
    && unzip duckdb.zip
  
ENV PATH="/app:$PATH"

COPY . .

CMD ["duckdb", "-cmd", ".read 'startup.sql'"]
EXPOSE 9999

when i execute the request inside the container, it's done, but, it's dont work outside!

is a problem of duckdb? 

Obs: i check the firewall, but, the container is clean of others executors and the top has only duckdb process in "background"

Thanks!

**Comment by lmangani** [comment]
Hello @qweralfredo
If you want the API run in foreground while in-process set `DUCKDB_HTTPSERVER_FOREGROUND=1`

For the same out-of-process you want to consider the reverse-twin of this extension [quackpipe](https://github.com/metrico/quackpipe)

**Comment by qweralfredo** [comment]
thanks @lmangani! 

But, its dont works, but, it's run perferctly in docker (local) and when i using ngrok tunnel access.

i'll recreate it!

**Comment by vhiairrassary** [comment]
> is a problem of duckdb?

No, it works very well.

Dockerfile
```Dockerfile
# syntax=docker/dockerfile:1
# check=error=true

FROM docker.io/library/debian:bookworm-slim AS base


# Throw-away build stage to reduce size of final image
FROM base AS build

# Set environment
ENV DUCKDB_VERSION="1.1.3"

# Install packages needed to install DuckDB
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
      ca-certificates \
      curl \
      unzip

RUN curl \
      --fail --silent --location \
      "https://github.com/duckdb/duckdb/releases/download/v${DUCKDB_VERSION}/duckdb_cli-linux-$(uname -m).zip" \
      -o ./duckdb.zip && \
    unzip ./duckdb.zip


# Final stage for app image
FROM base

# Copy built artifacts
COPY --from=build /duckdb /duckdb

ENTRYPOINT ["/duckdb"]
```

Then

```
bash
podman build -t my-duckdb-image .

podman run -ti \
  --init \
  -p 4000:4000 \
  -e 'DUCKDB_HTTPSERVER_DEBUG=1' \
  -e 'DUCKDB_HTTPSERVER_FOREGROUND=1' \
  my-duckdb-image \
  -c "INSTALL httpserver FROM community;" \
  -c "LOAD httpserver;" \
  -c "SELECT httpserve_start('0.0.0.0', 4000, '');"
```

(it downloads the extension, and won't output anything)

You can then use it with something like
```bash
curl -X POST -d "SELECT 'World' as Hello" "http://localhost:4000"
```

**Comment by lmangani** [comment]
What a *fantastic* example thanks for sharing it with the community @vhiairrassary I'm sure other users will treasure it

> No, it works very well.
