### ISSUE TITLE
configurable url_base to enable httpserve_start with path based routing (for example http://localhost:9999/duckserve/) - enabling simpler reverse proxying

### ISSUE THREAD

**Issue by mskyttner** [quackscience/duckdb-extension-httpserver#22]
When experimenting with running the httpserver extensions in a container, I tried putting the duckb CLI with the httpserver extension running behind a reverse proxy. So we then have a service/container running, lets call it "duckserve", and it has the httpserver started which binds to 0.0.0.0:9999 for example inside that container. It is not exposed to the outside world / larger network - instead it only accepts connections only from another service, which is a reverse proxy routing the traffic in to the service.

The reverse proxy runs in another process/container (running at say :80 and :443), which is exposed to the wider network with a more accessible name. It receives traffic and routes requests like "https://someserver.org/duckserve" to the upstream "duckserve" service (while taking care of other things like certificates for https etc).

It would be nice if the "duckserve" service could be configured to be available on a subpath when it is started. To understand the problem, see [this link about reverse proxying a service under a subdir / path based route](https://caddy.community/t/the-subfolder-problem-or-why-cant-i-reverse-proxy-my-app-into-a-subfolder/8575#understanding-the-problem-1).

If httpserver could be started with a setting for the “URL Base” it could then be reverse proxied along with other services from just one server under one subdomain/name, rather than requiring a separate subdomain ("stealing the webroot") for itself, because the reverse proxy wouldn't be required to "give up the webroot" to route traffic specifically to httpserver.

Would supporting something like `httpserve_start('0.0.0.0', 9999, 'auth', '/duckserve/')` be a possibility? Where the fourth parameter provides the path/route where the service is available (now I believe it is implicitly "/" ie the webroot). If so, I guess the web UI may already support it, if it gets the parameter "url"? 

Not sure the explanation above makes sense but if it was possible to provide this "subdir" at startup it would be possible to reverse proxy the service more easily, I think.

![image](https://github.com/user-attachments/assets/bfbc3ccd-7548-4f22-91fa-c5ae8911bac8)

**Comment by lmangani** [comment]
Might be as simple as #23 (I prefer ENV variables to function settings to keep things clean)

**Comment by mskyttner** [comment]
Wow, I barely sent the issue and there is a PR up :) ... sounds even better with the ENV!

**Comment by lmangani** [comment]
Implemented with #23 will be part of next release
