### ISSUE TITLE
Add wait mode for cli

### ISSUE THREAD

**Issue by blackrez** [quackscience/duckdb-extension-httpserver#7]
I don't know how (and if) it's possible, but it would be interesting to have a kind of wait mode. My use case is use duckdb with gcp cloud run, a serverless docker service. I imagine something like 
```duckdb :memory: "LOAD httpserver;  SELECT httpserve_start('0.0.0.0', 9999, wait=true); ``` And duckdb wait until a signal kill the process.

**Comment by lmangani** [comment]
Hey @blackrez the server process gets killed if the parent exists, which should apply find to the DuckDB CLI terminating.
Could you explain in more detail what the wait mode should provide and/or show the current limitation? Let's make it work!

**Comment by blackrez** [comment]
When I launched my container, the duckdb process will stop immediately after the function was call. 
What I want is something that wait until a signal is send.
<img width="1418" alt="Capture d’écran 2024-10-15 à 15 18 54" src="https://github.com/user-attachments/assets/bab111a2-14d7-47e7-a445-0ab5df89f35d">

**Comment by lmangani** [comment]
Currently the serve function runs in a separate thread and returns to the DuckDB prompt as if a query succeeded with results, which I suppose causes your serverless execution to terminate. To have a blocking approach the server should run in the main thread and that's possible, but not sure desirable or free from side effects.... if you want you can try this locally: https://github.com/lmangani/duckdb-extension-httpserver/pull/8

**Comment by blackrez** [comment]
This is exactly what I need (and a lot of people I think).

**Comment by lmangani** [comment]
Alright we can add this in. The foreground mode works, but before merging we really need to work on proper thread termination to avoid data loss, corruption, etc.

**Comment by blackrez** [comment]
> Alright we can add this in. The foreground mode works, but before merging we really need to work on proper thread termination to avoid data loss, corruption, etc.Message ID: ***@***.***>
> 

Stupid question, but is duckdb_cli already handle all that situations ?

**Comment by lmangani** [comment]
DuckDB CLI is not DuckDB and our code runs in a separate thread inside an extension which means we have to make sure the states are propagated, etc. Which I'm no expert of but with this said, I've added the missing code to the branch and it seems to behave as expected if you wanna try it locally:

```bash
> git clone https://github.com/lmangani/duckdb-extension-httpserver
> cd duckdb-extension-httpserver
> git submodule update --init --recursive
> git checkout thread-options

# build the branch and set the foreground ENV
> GEN=ninja make
> export DUCKDB_HTTPSERVER_FOREGROUND=1

# test it
> ./build/release/duckdb
```

**Comment by lmangani** [comment]
@blackrez does the implementation match your usecase?

**Comment by blackrez** [comment]
@lmangani it matches with my usecase.

**Comment by lmangani** [comment]
merged, will be part of next release (no WIN32 support)
